### ISSUE TITLE
URL is none

### ISSUE THREAD

**Issue by Cc47** [sefaburakokcu/yolov3-facial-landmark-detection#4]
https://drive.google.com/file/d/1_gVszd6i7LtiaTTiOj_zef91Qz-ehGDE/view?usp=sharing   
Sorry ，this website cannot be opened.I can't download any from this,please give me a new website,thanks!

**Comment by sefaburakokcu** [comment]
Hi, thank you for your interest! You can also download pre-trained weights from [here](https://www.dropbox.com/s/d8n1lj2tyarvp7n/pretrained_weights.zip?dl=0).

**Comment by Cc47** [comment]
> Hi, thank you for your interest! You can also download pre-trained weights from [here](https://www.dropbox.com/s/d8n1lj2tyarvp7n/pretrained_weights.zip?dl=0).

THANKS!Please read my last question and reply me,I need your help!!! I am anticipating your reply！
